# Generated by Django 2.2.4 on 2019-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dateOfBirth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hashpassword', models.CharField(max_length=1000)),
                ('confirmationCode', models.CharField(max_length=10)),
                ('confirmationStatus', models.CharField(max_length=2)),
                ('onlineStatus', models.CharField(max_length=2)),
                ('createdDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='postType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pType', models.CharField(max_length=50)),
            ],
        ),
    ]
