# Generated by Django 2.2.1 on 2019-10-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191022_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Account')),
            ],
        ),
    ]
