# Generated by Django 2.2.1 on 2019-10-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_saved_posts'),
        ('posts', '0002_auto_20191021_1514'),
        ('posts', '0006_savedpost'),
    ]

    operations = [
    ]
