# Generated by Django 2.2.1 on 2019-10-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20191025_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphicsName', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='savedPost',
        ),
    ]
