# Generated by Django 2.2.4 on 2019-10-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_videocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(blank=True, max_length=10000000, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
