# Generated by Django 2.2.1 on 2019-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191026_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
