# Generated by Django 2.2.4 on 2019-10-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_editdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='redLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('imageComment', models.TextField(blank=True, null=True)),
                ('videoComment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='greenLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('imageComment', models.TextField(blank=True, null=True)),
                ('videoComment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
