# Generated by Django 2.2.4 on 2019-10-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_greenlight_redlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenlight',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redlight',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
