# Generated by Django 2.2.1 on 2019-11-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20191031_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('imageComment', models.TextField(blank=True, null=True)),
                ('videoComment', models.TextField(blank=True, null=True)),
                ('lightType', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='redlight',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='redlight',
            name='post',
        ),
        migrations.DeleteModel(
            name='greenLight',
        ),
        migrations.DeleteModel(
            name='redLight',
        ),
    ]
