# Generated by Django 2.2.4 on 2019-11-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191101_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postType',
        ),
    ]
