# Generated by Django 2.2.4 on 2019-11-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_genuineblogers'),
    ]

    operations = [
        migrations.CreateModel(
            name='follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloger', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Account')),
            ],
        ),
    ]
